POST http://localhost:3333/videos
content-type: application/json

{
    "title": "Video test",
    "description": "Esse é o primeiro vídeo",
    "duration": 150
}

###

GET http://localhost:3333/videos?search=

###

PUT http://localhost:3333/videos/408383c6-7816-4040-a115-c99ebc4e8cc5
content-type: application/json

{
    "title": "Video 02",
    "description": "Esse é o primeiro vídeo",
    "duration": 100
}

###

DELETE http://localhost:3333/videos/76548290-f594-4314-be50-158886941089